"""empty message

Revision ID: 252e0698aee7
Revises: 5ac95f9e56d7
Create Date: 2026-02-02 17:09:56.924498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252e0698aee7'
down_revision = '5ac95f9e56d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protection_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'protection_files', ['file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protection_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
