"""empty message

Revision ID: 5ac95f9e56d7
Revises: bd18b4e571c6
Create Date: 2026-02-02 16:38:07.114427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac95f9e56d7'
down_revision = 'bd18b4e571c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protection_files', schema=None) as batch_op:
        batch_op.alter_column('protection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('protections_questions', schema=None) as batch_op:
        batch_op.alter_column('protection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protections_questions', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('protection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('protection_files', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('protection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
