"""empty message

Revision ID: 5cd7c9e1474d
Revises: 252e0698aee7
Create Date: 2026-02-05 15:33:01.296912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd7c9e1474d'
down_revision = '252e0698aee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('questions_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('questions_count')
        batch_op.drop_column('is_test')

    # ### end Alembic commands ###
